[tool.bandit]
exclude = ['app/scripts/*.py',"alembic", "terraform", ".pytest_cache", '**test*.py']
skips = ["B101", "B106", "B311"]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
profile = "black"
combine_as_imports = true
force_alphabetical_sort_within_sections = true
lines_between_types = 0
src_paths = ["./", "./app/"]
known_third_party = []
known_first_party = []
